### ISSUE TITLE
[Bug]: When calculation is not done (Could not create a feasible schedule), grid setpoint is not reverted to 0

### ISSUE THREAD

**Issue by khostri** [victronenergy/dynamic-ess#26]
### Contact Details

jan.slaby@outlook.com

### VRM / Site iD

210204

### Country / region

Czech Republic (cz)

### B max

20

### TB max

8.5

### FB max

8.5

### TG max

9.9

### FG max

12

### Battery costs

0.06

### Buy price

(p+0.150675)*1.21

### Sell price

(p-0.0276)*1.21

### feed-in possible

yes

### feed-in possible

yes

### What happened?

During today's testing now I get message Could not create a feasible schedule. I suppose its because of calculation was not successful. But grid setpoint was left at -9900 so batery started to cycle: Discharge into grid to 45% (Life optimized settings), charged to 50%, discharged to 45% etc. Discharge energy was max configured in node.
I had to setup gridpoint manually to 0 in remote console.

### Screenshots

![image](https://github.com/victronenergy/dynamic-ess/assets/10581890/270bd4f3-341e-4d8c-8fac-1abfe1e49fc8)
![image](https://github.com/victronenergy/dynamic-ess/assets/10581890/dfe2b72d-9d1e-47b7-bbf3-e837127b5701)

**Comment by dirkjanfaber** [comment]
We've just published a new release, that is more incorporated into the Venus OS and follows the target SOC instead of setting a setpoint and a less than ideal way of idling the battery.

As this uses a different approach, you will need to:
- update Venus OS (to 3.10 or above)
- update the victron-dynamic-ess node to version 0.1.1
- update the example flow
- reconfigure the Dynamic ESS node

More information can be found in the [release notes](https://github.com/victronenergy/dynamic-ess/blob/main/RELEASE-NOTES.md) and [README.md](https://github.com/victronenergy/dynamic-ess/blob/main/README.md)

Regarding this issue, the new flow will set a schedule for the next 4 hours and will switch Dynamic ESS off if no new schedules can be fetched from the API.
