### ISSUE TITLE
[Bug]: Could not create a feasible schedule

### ISSUE THREAD

**Issue by andressade** [victronenergy/dynamic-ess#32]
### VRM / Site iD

285851

### Country / region

Estonia (ee)

### B max

7.5

### TB max

2

### FB max

2

### TG max

0.72

### FG max

2

### Battery costs

0.04

### Buy price

(p+0.0044+0.0394)*1.2

### Sell price

p-0.0075

### feed-in possible

yes

### feed-in possible

yes

### What happened?

After enabling Dynamic ESS node the error "Could not create a feasible schedule" will be displayed. Api info output shows http 500 "Internal Server Error"

### Screenshots

```bash

```

**Comment by andressade** [comment]
<img width="1452" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/6726065/7fa4f0d4-abfb-471b-83c8-299bd5418640">

**Comment by dirkjanfaber** [comment]
Have you set the location in the VRM for the site?

**Comment by Mableeker** [comment]
Same sort of situation here, small difference that in node-red flow it shows ok, but in the dashboard is says 'could not create a feasible schedule', although the graphs show a good schedule but the multiplus doesn't obey the schedule. Settings are not set...![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/93a26ac5-a648-4055-b5ac-941f3e9932d7)

**Comment by mrstackit** [comment]
I have the same issue in the flow and ui shows: Could not create a feasible schedule. I have do the initial Setup today and after a few hours this problem.

**Comment by mpvader** [comment]
We're looking into this (Ali is)

**Comment by PoolsideKelbi** [comment]
Hey @mrstackit, thanks for reporting this error.

This issue should be solved now. The low value of TG_max made it difficult for Dynamic ESS to schedule the rest of the day. But now it should be able to deal with values such as these.

Please give it a check and in the case that it works, feel free to close the issue :)

**Comment by mrstackit** [comment]
Hey @PoolsideKelbi thanks for your reaction,

In the flow everything looks fine in the UI (dashboard the message is still there) even after restarting the flow. I activated the flow again at the weekend and just let it run. However, since 1 p.m. today, I have noticed strange behavior. The day was well planned until 1 p.m. Then it was somehow rescheduled and it suddenly started charging at 25 cents kWh, which made no sense. Also visible in the screenshots. No loading was planned there before 1 p.m. At 25 cents kWh it makes no sense to charge the battery if the most expensive price is around 30 cents. I am not the first person to report the bug, my settings in the flow are different:

Country: Germany
B max: 2.4
TB max: 1.2
FB max: 1.2
TG max: 0
FG max: 10

Should I open a new bug for this?

![grafik](https://github.com/victronenergy/dynamic-ess/assets/80634441/95d2fa69-0f63-49bd-9a4f-5b1b089f49b3)
![grafik](https://github.com/victronenergy/dynamic-ess/assets/80634441/3cf542c2-617d-47a3-8d6b-9576608e7dd0)

**Comment by mrstackit** [comment]
Today again at 2pm fg_max is set at price 0,24 € kWh at SOC is on 90%. Thats bad. Prices in the evening max 0,32 € for two hours. Can you tell me why he suddenly sets fg_max even though it's not worth it? How is it calculated when the battery is charged from the grid?
