### ISSUE TITLE
[Bug]: See issue #61 - Charging with handbrakes on

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#64]
### Contact Details

siempoot@gmail.com

### VRM portal ID

c0619ab31cc4

### Country / region

Netherlands (nl)

### B max

40

### TB max

not relevant

### FB max

not relevant

### TG max

not relevant

### FG max

not relevant

### Battery costs

not relevant

### Buy price

not relevant

### Sell price

not relevant

### feed-in possible

None

### feed-in possible

None

### Version

0.1.3

### What happened?

A bug may have happened:

The system is still not charging with maximum power (i would expect 6kW from the Multiplusses and 1.4kW from DC). I am at the latest version, and the proper battery capacity is in (40).
I do not know if this is on purpose (to incur less losses from the Multiplus (3x)) or that something is wrong
![VESS - Screenshot 2023-09-15 131133](https://github.com/victronenergy/dynamic-ess/assets/139110412/e3038f29-78b5-477a-852b-f5e8761fc907)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
The system will take the full hour to get to the target SOC instead of going there as fast as possible. This is done not to stress the system more than needed and to be in line with what is intended with the energy pricing concept. Imagine all of our users start dumping in the first 15 minutes of the hour and not doing anything for the rest of the hour.

Looking at yesterdays vrmlogger data of your site, you can see that the target almost always gets reached at the end of the hour.

![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/d7f01827-bbce-43af-ad64-e622722a1a52)
