### ISSUE TITLE
[Bug]: Dead-Zone in planning

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#91]
### Contact Details

siempoot@gmail.com

### VRM portal ID

c0619ab31cc4

### Country / region

Netherlands (nl)

### B max

40

### TB max

6

### FB max

6

### TG max

16

### FG max

16

### Battery costs

0.027

### Buy price

(p+0.13)*1.21+0.02

### Sell price

(p+0.13)*1.21-0.02

### feed-in possible

yes

### feed-in control

None

### Version

0.1.6

### What happened?

The planning shows a dead-zone. I do not think this is correct.

![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/4b9d0868-f097-4040-981b-d337b9febcd8)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/21f07802-3089-436b-b534-69cd4a19f6ba)

**Comment by SimonYoungtree** [comment]
After a number of hours (I do not know exactly when), some consumption was planned again. Perhaps history on VRM could not be compiled for some reason?

**Comment by andreashackel** [comment]
I could also observe this problem in my system environment (Node Red V.0.1.7). In the last 8 days there was only one day without zero data in the consumption forecast. Otherwise the problem occurs after 13:00 and is solved by a recalculation after 4 to 8 hours. Today (20231015) I was able to take a closer look.
As usual, after 13:00 the consumption forecast changed a lot, but today it did not go to zero, but to a very small value (< 10Wh). Since I have a base load of about 250 Wh in my house, this forecast is not plausible. (Is it possible that only the grid consumption is taken into account and not the battery consumption?) A recalculation around 14:30 corrected the planned consumption to plausible values around 800 Wh.

20231015 12:52 (On this day in the period from 18:00 to 24:00.)
![grafik](https://github.com/victronenergy/dynamic-ess/assets/126014883/ca89db40-f463-43b0-b40d-b2e7ff06efde)
20231015 13:12
![grafik](https://github.com/victronenergy/dynamic-ess/assets/126014883/a931fe0b-3d2d-42fc-ac39-300bd3ce1b12)
20231015 14:25
![grafik](https://github.com/victronenergy/dynamic-ess/assets/126014883/036689cc-5429-4bb5-be1e-cc5e6176e57a)

**Comment by SamuelBrucksch** [comment]
I have the same issue on VRM beta:
![image](https://github.com/victronenergy/dynamic-ess/assets/8776268/4dae8fcb-6110-4b49-b5b4-a81fa7d6c223)

**Comment by dirkjanfaber** [comment]
Closing this issue as it has been open for too long; new releases have been out. If it still occurs with the latest release, please open a new issue.
